[package]
name = "react-reconciler"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.84"
web-sys = { version = "0.3.69", features = [
    "console",
    "Text",
    "Window",
    "Document",
    "HtmlElement",
] }
react = { path = "../react" }
shared = { path = "../shared" }
scheduler = { path = "../scheduler" }
console_error_panic_hook = { version = "0.1.7", optional = true }
bitflags = "2.5.0"


[dev-dependencies]
wasm-bindgen-test = "0.3.34"

[profile.release]
opt-level = "s"
