[package]
name = "react-dom"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.84"
web-sys = { version = "0.3.69", features = [
    "console",
    "Window",
    "Document",
    "Text",
    "Element",
    "EventListener",
] }
react-reconciler = { path = "../react-reconciler" }
shared = { path = "../shared" }
# scheduler = { path = "../scheduler" }
console_error_panic_hook = { version = "0.1.7", optional = true }
gloo = "0.11.0"
js-sys = "0.3.69"

[dev-dependencies]
wasm-bindgen-test = "0.3.34"

[profile.release]
opt-level = "s"
